spring.application.name=MessageBoardAPI
spring.datasource.url=jdbc:sqlite:MessageBoardDB.db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect